### ISSUE TITLE
G3X RS-232 Format missing Attitude/Air Data Sentence 2

### ISSUE THREAD

**Issue by midwestpanels** [flyonspeed/TronView#51]
The G3X Serial shows DA as a to-do, and calculates TAS from Air Data Set 1. This information, in addition to heading bug, altitude bug, airspeed bug, and VS bug are all available in Air Data Set 2 (sentence ID 2, ver 1).

I plan to submit a PR that addresses and solves this.

**Comment by hpmicrowave** [comment]
👍Sent from my iPhoneOn Jul 27, 2024, at 3:52 PM, midwestpanels ***@***.***> wrote:﻿
The G3X Serial shows DA as a to-do, and calculates TAS from Air Data Set 1. This information, in addition to heading bug, altitude bug, airspeed bug, and VS bug are all available in Air Data Set 2 (sentence ID 2, ver 1).
I plan to submit a PR that addresses and solves this.

**Comment by midwestpanels** [comment]
The scope of this issue has evolved into debugging and testing more of the G3X serial input, as well as refactoring many of the data inputs, like changing calculated inputs into ones already provided by the G3X RS-232 format.

PR #52 currently has the following improvements/changes:
- Added Sentence ID 2 to the input parsing
- Moved DAlt, TAS to SID 2
- Changed SID detection from byte integer to decoded UTF-8 string to address a crash that could happen if the "CNI" output was enabled on the G3X
- Moved Ground Speed from calculated value based on "@" GPS input to SID 7 input
- Fixed SID 7 input length (mismatch between actual sentence length and expected sentence length) to solve no AGL issue and allow GPS Ground Speed to be brought in instead of calculated
- Modified hud_utils to use fullpath instead of dirname on line 204 to solve crash due to dirname not being defined
- Bumped serial_g3x to v1.2
