### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by Mrcoole7890** [flyonspeed/TronView#59]
Good Afternoon, 

I attempted to join the discord listed on the readme.md and it appears to be not working.
I would like to try my hand at an open source project to contribute to.

Cheers

**Comment by hpmicrowave** [comment]
Hi. Glad you contacted me.  Tell me a little about yourself and what aircraft you fly and why your interested in our project?  ThanksTRON. Sent from my iPhoneOn Oct 13, 2024, at 6:26 PM, Mrcoole7890 ***@***.***> wrote:﻿
Good Afternoon,
I attempted to join the discord listed on the readme.md and it appears to be not working.
I would like to try my hand at an open source project to contribute to.
Cheers

**Comment by Mrcoole7890** [comment]
Hello, 

My name is Cole. I am software development enthusiast. I worked as a QA automation engineer with GlobalLogic for a year and some change around the years 2022 and 2023 (mostly web applications and endpoint testing). I personally don't fly; however, a relative of mine who has flown in the air force pointed me in this direction. I am working as a server at a restaurant and I would like to join a project to stay sharp in my preferred profession.

**Comment by TopherTimeMachine** [comment]
fixed.  I updated the discord link.
