### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ScreenObjects'

### ISSUE THREAD

**Issue by Mrcoole7890** [flyonspeed/TronView#65]
I am attempting to run a demo in text mode; however, I keep getting this error. I have tried messing with the config file and doing various tweaks.

Here is the command and the subsequent message: 

`sudo python3 main.py -i serial_g3x -t -e`

Error Log: 

```
pygame-ce 2.5.2 (SDL 2.30.8, Python 3.11.2)
aarch64
Input data module 0: serial_g3x
aarch64
Opening Logfile: lib/inputs/_example_data/garmin_g3x_data1.txt
speed distance format: mph 
temperature format: C 
Traceback (most recent call last):
  File "/home/cole/TronView/main.py", line 266, in <module>
    edit_save_load.load_screen_from_json("default.json",from_templates=True)
  File "/home/cole/TronView/lib/common/graphic/edit_save_load.py", line 33, in load_screen_from_json
    shared.CurrentScreen.ScreenObjects = []
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ScreenObjects'

```
config.cfg:
```
# Example of config file.  Change this file and save as config.cfg

[Main]
# if "window" is set then screen will run in windowed mode if running in xwindows or other window type os.
# this is the size of the waveshare lcd screen
#window=1280,400
# small screen size
#window=640,480
#window=1280,768

#drawable_area is used to set the boundry for where the efis can draw on the screen.
#For Epic HUD use the following
#drawable_area=0,159,1280,651

# Show Mouse? set to true if you want to show the mouse. Defaults to false
#showMouse = true

#Which screen to run on startup.. "Default" screen is used if nothing entered.
screen = Default

# Set max frame rate. defaults to 30
#maxframerate = 30

# Ignore any traffic targets beyond a given distance in miles (defaults to importing all traffic into aircraft traffic object)
#ignore_traffic_beyond_distance = 5

[DataInput]
# Set input source. options are in the /lib/inputs/ folder
#inputsource = serial_d100
#inputsource = serial_skyview
#inputsource = serial_mgl
inputsource = serial_g3x
#inputsource = levil_wifi
#inputsource = serial_logger
#inputsource = stratux_wifi
#inputsource = adc_ads1115


# Set serial port. defaults to /dev/ttyS0
# rpi built in serial is /dev/ttyS0
# rpi usb serial is /dev/ttyUSB0
#port = /dev/ttyS0

[DataInput2]
# set this to use a 2nd data input source
# 2nd input source will overwrite the data from the 1st source (if data exists)
#inputsource = stratux_wifi

[DataInput3]
# set this to use a 3rd data input source
# 2nd input source will overwrite the data from the 1st source (if data exists)
#inputsource = adc_ads1115

[Stratux]
# To ignore ahrs data from stratux set use_ahrs=false, defaults to true
#use_ahrs = false

# set UPD port for network input.. defaults to 4000
#udpport = 4000

[Formats]
# Set speed and distance to Knots, Standard, Metric (default is Standard)
#speed_distance = Metric
# Set temperate to F or C (defaults to F)
#temperature = C

[DataRecorder]
# change the path were the default flight log files are saved. Make sure this dir exists.
# default path is /flightlog/
#path = /flightlog/

# check if usb drive is available for creating log files?
# defaults to true
#check_usb_drive = true


[HUD]
#HUD settings.

# how thick to draw hud lines... defaults to 2 pixels
#line_thickness = 2

# how many vertical degrees to have per line seperation. default 5
#vertical_degrees = 5

# line mode.  can be 0 or 1.
#line_mode = 1

# center circle radius. default 4
#center_circle = 4

#field of view width in degrees. This is the total number of degrees for the FOV  Defaults to 13.942
#fov_x = 13.942

# pixel per degree for hud.  default is 30.
#vertical_pixels_per_degree = 30

# show traffic within mileage range.  defaults to 5
# this shows traffic targets in HUD view that are less then X miles distance from aircraft.
# if set to 0 then don't show any traffic data.
#show_traffic_within_miles = 5

# font size for target details.  default 40
#target_font_size = 40

# Set Horizon Center Offset in Pixels (- = Up/+ = Down) (Default is 0)
#Horizon_Offset = -100

[TrafficScope]
# Traffic Scope settings.

# target font size default 16
#target_font_size = 16

# show target lat/lon default is false
#target_show_lat_lon = true

[F18_HUD]
# F18 hud options.

# show aircraft lat/lon on F18 HUD default is false
#show_lat_lon = false

```

**Comment by hpmicrowave** [comment]
Give me a call please. At 850-496-0464.  Sent from my iPhoneOn Nov 3, 2024, at 7:14 PM, Mrcoole7890 ***@***.***> wrote:﻿
I am attempting to run a demo in text mode; however, I keep getting this error. I have tried messing with the config file and doing various tweaks.
Here is the command and the subsequent message:
sudo python3 main.py -i serial_g3x -t -e
Error Log:
pygame-ce 2.5.2 (SDL 2.30.8, Python 3.11.2)
aarch64
Input data module 0: serial_g3x
aarch64
Opening Logfile: lib/inputs/_example_data/garmin_g3x_data1.txt
speed distance format: mph 
temperature format: C 
Traceback (most recent call last):
  File "/home/cole/TronView/main.py", line 266, in <module>
    edit_save_load.load_screen_from_json("default.json",from_templates=True)
  File "/home/cole/TronView/lib/common/graphic/edit_save_load.py", line 33, in load_screen_from_json
    shared.CurrentScreen.ScreenObjects = []
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ScreenObjects'


config.cfg:
# Example of config file.  Change this file and save as config.cfg

[Main]
# if "window" is set then screen will run in windowed mode if running in xwindows or other window type os.
# this is the size of the waveshare lcd screen
#window=1280,400
# small screen size
#window=640,480
#window=1280,768

#drawable_area is used to set the boundry for where the efis can draw on the screen.
#For Epic HUD use the following
#drawable_area=0,159,1280,651

# Show Mouse? set to true if you want to show the mouse. Defaults to false
#showMouse = true

#Which screen to run on startup.. "Default" screen is used if nothing entered.
screen = Default

# Set max frame rate. defaults to 30
#maxframerate = 30

# Ignore any traffic targets beyond a given distance in miles (defaults to importing all traffic into aircraft traffic object)
#ignore_traffic_beyond_distance = 5

[DataInput]
# Set input source. options are in the /lib/inputs/ folder
#inputsource = serial_d100
#inputsource = serial_skyview
#inputsource = serial_mgl
inputsource = serial_g3x
#inputsource = levil_wifi
#inputsource = serial_logger
#inputsource = stratux_wifi
#inputsource = adc_ads1115


# Set serial port. defaults to /dev/ttyS0
# rpi built in serial is /dev/ttyS0
# rpi usb serial is /dev/ttyUSB0
#port = /dev/ttyS0

[DataInput2]
# set this to use a 2nd data input source
# 2nd input source will overwrite the data from the 1st source (if data exists)
#inputsource = stratux_wifi

[DataInput3]
# set this to use a 3rd data input source
# 2nd input source will overwrite the data from the 1st source (if data exists)
#inputsource = adc_ads1115

[Stratux]
# To ignore ahrs data from stratux set use_ahrs=false, defaults to true
#use_ahrs = false

# set UPD port for network input.. defaults to 4000
#udpport = 4000

[Formats]
# Set speed and distance to Knots, Standard, Metric (default is Standard)
#speed_distance = Metric
# Set temperate to F or C (defaults to F)
#temperature = C

[DataRecorder]
# change the path were the default flight log files are saved. Make sure this dir exists.
# default path is /flightlog/
#path = /flightlog/

# check if usb drive is available for creating log files?
# defaults to true
#check_usb_drive = true


[HUD]
#HUD settings.

# how thick to draw hud lines... defaults to 2 pixels
#line_thickness = 2

# how many vertical degrees to have per line seperation. default 5
#vertical_degrees = 5

# line mode.  can be 0 or 1.
#line_mode = 1

# center circle radius. default 4
#center_circle = 4

#field of view width in degrees. This is the total number of degrees for the FOV  Defaults to 13.942
#fov_x = 13.942

# pixel per degree for hud.  default is 30.
#vertical_pixels_per_degree = 30

# show traffic within mileage range.  defaults to 5
# this shows traffic targets in HUD view that are less then X miles distance from aircraft.
# if set to 0 then don't show any traffic data.
#show_traffic_within_miles = 5

# font size for target details.  default 40
#target_font_size = 40

# Set Horizon Center Offset in Pixels (- = Up/+ = Down) (Default is 0)
#Horizon_Offset = -100

[TrafficScope]
# Traffic Scope settings.

# target font size default 16
#target_font_size = 16

# show target lat/lon default is false
#target_show_lat_lon = true

[F18_HUD]
# F18 hud options.

# show aircraft lat/lon on F18 HUD default is false
#show_lat_lon = false

**Comment by hpmicrowave** [comment]
I’m sorry but I can’t find a copy here at my house of the Raspberry Pi 4 HUD SW image.   I sure there is a copy at my hangar but I won’t be going back there till Tuesday.   I’ll reload it back to the drive when I get back to the hangar. Sent from my iPhoneOn Nov 3, 2024, at 7:25 PM, Cecil Jones ***@***.***> wrote:﻿Give me a call please. At 850-496-0464.  Sent from my iPhoneOn Nov 3, 2024, at 7:14 PM, Mrcoole7890 ***@***.***> wrote:﻿
I am attempting to run a demo in text mode; however, I keep getting this error. I have tried messing with the config file and doing various tweaks.
Here is the command and the subsequent message:
sudo python3 main.py -i serial_g3x -t -e
Error Log:
pygame-ce 2.5.2 (SDL 2.30.8, Python 3.11.2)
aarch64
Input data module 0: serial_g3x
aarch64
Opening Logfile: lib/inputs/_example_data/garmin_g3x_data1.txt
speed distance format: mph 
temperature format: C 
Traceback (most recent call last):
  File "/home/cole/TronView/main.py", line 266, in <module>
    edit_save_load.load_screen_from_json("default.json",from_templates=True)
  File "/home/cole/TronView/lib/common/graphic/edit_save_load.py", line 33, in load_screen_from_json
    shared.CurrentScreen.ScreenObjects = []
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ScreenObjects'


config.cfg:
# Example of config file.  Change this file and save as config.cfg

[Main]
# if "window" is set then screen will run in windowed mode if running in xwindows or other window type os.
# this is the size of the waveshare lcd screen
#window=1280,400
# small screen size
#window=640,480
#window=1280,768

#drawable_area is used to set the boundry for where the efis can draw on the screen.
#For Epic HUD use the following
#drawable_area=0,159,1280,651

# Show Mouse? set to true if you want to show the mouse. Defaults to false
#showMouse = true

#Which screen to run on startup.. "Default" screen is used if nothing entered.
screen = Default

# Set max frame rate. defaults to 30
#maxframerate = 30

# Ignore any traffic targets beyond a given distance in miles (defaults to importing all traffic into aircraft traffic object)
#ignore_traffic_beyond_distance = 5

[DataInput]
# Set input source. options are in the /lib/inputs/ folder
#inputsource = serial_d100
#inputsource = serial_skyview
#inputsource = serial_mgl
inputsource = serial_g3x
#inputsource = levil_wifi
#inputsource = serial_logger
#inputsource = stratux_wifi
#inputsource = adc_ads1115


# Set serial port. defaults to /dev/ttyS0
# rpi built in serial is /dev/ttyS0
# rpi usb serial is /dev/ttyUSB0
#port = /dev/ttyS0

[DataInput2]
# set this to use a 2nd data input source
# 2nd input source will overwrite the data from the 1st source (if data exists)
#inputsource = stratux_wifi

[DataInput3]
# set this to use a 3rd data input source
# 2nd input source will overwrite the data from the 1st source (if data exists)
#inputsource = adc_ads1115

[Stratux]
# To ignore ahrs data from stratux set use_ahrs=false, defaults to true
#use_ahrs = false

# set UPD port for network input.. defaults to 4000
#udpport = 4000

[Formats]
# Set speed and distance to Knots, Standard, Metric (default is Standard)
#speed_distance = Metric
# Set temperate to F or C (defaults to F)
#temperature = C

[DataRecorder]
# change the path were the default flight log files are saved. Make sure this dir exists.
# default path is /flightlog/
#path = /flightlog/

# check if usb drive is available for creating log files?
# defaults to true
#check_usb_drive = true


[HUD]
#HUD settings.

# how thick to draw hud lines... defaults to 2 pixels
#line_thickness = 2

# how many vertical degrees to have per line seperation. default 5
#vertical_degrees = 5

# line mode.  can be 0 or 1.
#line_mode = 1

# center circle radius. default 4
#center_circle = 4

#field of view width in degrees. This is the total number of degrees for the FOV  Defaults to 13.942
#fov_x = 13.942

# pixel per degree for hud.  default is 30.
#vertical_pixels_per_degree = 30

# show traffic within mileage range.  defaults to 5
# this shows traffic targets in HUD view that are less then X miles distance from aircraft.
# if set to 0 then don't show any traffic data.
#show_traffic_within_miles = 5

# font size for target details.  default 40
#target_font_size = 40

# Set Horizon Center Offset in Pixels (- = Up/+ = Down) (Default is 0)
#Horizon_Offset = -100

[TrafficScope]
# Traffic Scope settings.

# target font size default 16
#target_font_size = 16

# show target lat/lon default is false
#target_show_lat_lon = true

[F18_HUD]
# F18 hud options.

# show aircraft lat/lon on F18 HUD default is false
#show_lat_lon = false

**Comment by Mrcoole7890** [comment]
This works as expected now. There was a code change that fixed this.

![image](https://github.com/user-attachments/assets/dd948eae-5be4-48d7-b605-7af61902c925)
